---
name: test_and_build

env:
  KOHA_RELEASE: canary
  KOHA_IMAGE: main-bookworm
  DB_IMAGE: mariadb:10.11
  KDD_IMAGE: main

on:
  push:

jobs:
  test:
    runs-on:
      - bare-metal
      - arm64
    steps:
      - uses: actions/checkout@v4
      - run: |
             perl ${FORGEJO_WORKSPACE}/.forgejo/helpers/download_test_tools.pl
      - run: |
             perl ${JENKINS_HELPER_SCRIPTS}/koha_tests_runner.pl \
                 --initial-docker-cleanup \
                 --run-light-test-suite \
                 --warmup-timeout 550 \
                 --force-cleanup \
                 --verbose
        timeout-minutes: 180
      - run: |
             perl ${FORGEJO_WORKSPACE}/.forgejo/helpers/cleanup_test_tools.pl

  build:
    runs-on:
      - bare-metal
      - arm64
    steps:
      - uses: actions/checkout@v4
      - run: |
             perl ${FORGEJO_WORKSPACE}/.forgejo/helpers/download_build_tools.pl
      - run: |
             perl ${KDD_HELPER_SCRIPTS}/build.pl
        timeout-minutes: 180
      - run: |
             perl ${FORGEJO_WORKSPACE}/.forgejo/helpers/cleanup_build_tools.pl
